import 'package:flutter/material.dart';
import 'report_model.dart';

class ReportRegistry {
  static final List<ReportDefinition> allReports = [
    // --- SPECIAL / COMPREHENSIVE REPORTS ---
    const ReportDefinition(
      id: 'individual_member_statement',
      titleMr: '★ व्यक्तिगत सभासद संपूर्ण अहवाल (Member Statement)',
      titleEn: 'Individual Member Comprehensive Statement',
      subtitle: 'निवडक सदस्याचे बचत, कर्ज, हप्ते, लेट फी व संपूर्ण व्यवहार अहवाल',
      category: ReportCategory.members,
      icon: Icons.account_box_rounded,
      supabaseTable: 'members',
      dateField: 'created_at',
      secondaryFilters: ['member'],
      columns: [],
    ),
    const ReportDefinition(
      id: 'monthly_bachatgat_ledger',
      titleMr: '★ मासिक बचत अहवाल (Monthly Bachatgat Ledger)',
      titleEn: 'Monthly Bachatgat Statement / Ledger',
      subtitle: 'पारंपरिक मराठी लेजर ग्रिड - कर्ज, हप्ता, व्याज व बचत मासिक अहवाल',
      category: ReportCategory.savings,
      icon: Icons.table_chart_rounded,
      supabaseTable: 'savings',
      dateField: 'savings_date',
      isLandscape: true,
      columns: [],
    ),

    // --- 1. MEMBER REPORTS ---
    const ReportDefinition(
      id: 'member_list',
      titleMr: '१. सदस्य यादी अहवाल (Member List)',
      titleEn: '1. Member List Report',
      subtitle: 'सर्व सक्रिय व नोंदणीकृत सभासदांची माहिती',
      category: ReportCategory.members,
      icon: Icons.people,
      supabaseTable: 'members',
      dateField: 'created_at',
      columns: [
        ReportColumn(key: 'sr_no', labelMr: 'अ.क्र.', labelEn: 'Sr.', flex: 0.5),
        ReportColumn(key: 'member_code', labelMr: 'सदस्य आयडी', labelEn: 'Member ID', flex: 1.0),
        ReportColumn(key: 'full_name', labelMr: 'नाव', labelEn: 'Name', flex: 2.0),
        ReportColumn(key: 'mobile_number', labelMr: 'मोबाईल', labelEn: 'Mobile', flex: 1.2),
        ReportColumn(key: 'gender', labelMr: 'लिंग', labelEn: 'Gender', flex: 0.8),
        ReportColumn(key: 'village', labelMr: 'गाव', labelEn: 'Village', flex: 1.0),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 0.8),
      ],
    ),
    const ReportDefinition(
      id: 'member_ledger',
      titleMr: '२. सदस्य खातेवही अहवाल (Member Ledger)',
      titleEn: '2. Member Ledger Report',
      subtitle: 'निवडक सदस्याचे जमा, नावे व चालू शिल्लक खाते',
      category: ReportCategory.members,
      icon: Icons.menu_book,
      supabaseTable: 'savings',
      dateField: 'savings_date',
      secondaryFilters: ['member'],
      columns: [
        ReportColumn(key: 'date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'particulars', labelMr: 'तपशील', labelEn: 'Particulars', flex: 2.2),
        ReportColumn(key: 'ref_no', labelMr: 'पावती/संदर्भ', labelEn: 'Ref No', flex: 1.2),
        ReportColumn(key: 'debit', labelMr: 'नावे (Debit)', labelEn: 'Debit', isNumeric: true, isCurrency: true, flex: 1.0),
        ReportColumn(key: 'credit', labelMr: 'जमा (Credit)', labelEn: 'Credit', isNumeric: true, isCurrency: true, flex: 1.0),
        ReportColumn(key: 'balance', labelMr: 'शिल्लक', labelEn: 'Balance', isNumeric: true, isCurrency: true, flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'member_statement',
      titleMr: '३. सदस्य स्टेटमेंट (Member Statement)',
      titleEn: '3. Member Statement',
      subtitle: 'सदस्याचे एकूण बचत, कर्ज व परतफेड विवरणपत्र',
      category: ReportCategory.members,
      icon: Icons.description,
      supabaseTable: 'savings',
      dateField: 'savings_date',
      secondaryFilters: ['member'],
      columns: [
        ReportColumn(key: 'date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'particulars', labelMr: 'तपशील', labelEn: 'Particulars', flex: 2.5),
        ReportColumn(key: 'debit', labelMr: 'नावे (₹)', labelEn: 'Debit (Rs)', isNumeric: true, isCurrency: true, flex: 1.0),
        ReportColumn(key: 'credit', labelMr: 'जमा (₹)', labelEn: 'Credit (Rs)', isNumeric: true, isCurrency: true, flex: 1.0),
        ReportColumn(key: 'balance', labelMr: 'शिल्लक (₹)', labelEn: 'Balance (Rs)', isNumeric: true, isCurrency: true, flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'member_savings',
      titleMr: '४. सदस्यनिहाय बचत अहवाल (Member Savings)',
      titleEn: '4. Member-wise Savings',
      subtitle: 'प्रत्येक सदस्याची कालावधीतील एकूण जमा बचत',
      category: ReportCategory.members,
      icon: Icons.person_pin,
      supabaseTable: 'savings',
      dateField: 'savings_date',
      columns: [
        ReportColumn(key: 'sr_no', labelMr: 'अ.क्र.', labelEn: 'Sr.', flex: 0.5),
        ReportColumn(key: 'member_code', labelMr: 'सदस्य आयडी', labelEn: 'Code', flex: 1.0),
        ReportColumn(key: 'full_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 2.2),
        ReportColumn(key: 'total_months', labelMr: 'महिने', labelEn: 'Months', isNumeric: true, flex: 0.8),
        ReportColumn(key: 'amount', labelMr: 'जमा बचत (₹)', labelEn: 'Saved (Rs)', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 0.8),
      ],
    ),
    const ReportDefinition(
      id: 'member_loans',
      titleMr: '५. सदस्यनिहाय कर्ज अहवाल (Member Loans)',
      titleEn: '5. Member-wise Loan',
      subtitle: 'सदस्यांनी घेतलेले कर्ज, परतफेड व थकीत मुद्दल',
      category: ReportCategory.members,
      icon: Icons.assignment_ind,
      supabaseTable: 'loans',
      dateField: 'application_date',
      columns: [
        ReportColumn(key: 'loan_code', labelMr: 'कर्ज क्र.', labelEn: 'Loan No', flex: 1.0),
        ReportColumn(key: 'member_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 2.0),
        ReportColumn(key: 'approved_amount', labelMr: 'मंजूर कर्ज (₹)', labelEn: 'Sanctioned', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'total_repaid', labelMr: 'परतफेड (₹)', labelEn: 'Repaid', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'outstanding_principal', labelMr: 'शिल्लक मुद्दल (₹)', labelEn: 'Outstanding', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 0.8),
      ],
    ),
    const ReportDefinition(
      id: 'member_attendance',
      titleMr: '६. सदस्य हजेरी अहवाल (Member Attendance)',
      titleEn: '6. Member Attendance Report',
      subtitle: 'मासिक सभांमधील उपस्थिती व गैरहजेरी टक्केवारी',
      category: ReportCategory.members,
      icon: Icons.how_to_reg,
      supabaseTable: 'meeting_attendance',
      dateField: 'created_at',
      columns: [
        ReportColumn(key: 'member_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 2.0),
        ReportColumn(key: 'total_meetings', labelMr: 'एकूण सभा', labelEn: 'Total Meets', isNumeric: true, flex: 1.0),
        ReportColumn(key: 'attended', labelMr: 'हजर', labelEn: 'Present', isNumeric: true, flex: 0.8),
        ReportColumn(key: 'absent', labelMr: 'गैरहजर', labelEn: 'Absent', isNumeric: true, flex: 0.8),
        ReportColumn(key: 'rate', labelMr: 'हजेरी %', labelEn: 'Rate %', isNumeric: true, flex: 1.0),
      ],
    ),

    // --- 2. SAVINGS REPORTS ---
    const ReportDefinition(
      id: 'monthly_savings',
      titleMr: '७. मासिक बचत अहवाल (Monthly Savings)',
      titleEn: '7. Monthly Savings Report',
      subtitle: 'कालावधीतील मासिक बचत संकलन, अपेक्षित व तफावत',
      category: ReportCategory.savings,
      icon: Icons.calendar_view_month,
      supabaseTable: 'savings',
      dateField: 'savings_date',
      columns: [
        ReportColumn(key: 'savings_date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'receipt_number', labelMr: 'पावती क्र.', labelEn: 'Receipt No', flex: 1.2),
        ReportColumn(key: 'member_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 2.0),
        ReportColumn(key: 'amount', labelMr: 'जमा रक्कम (₹)', labelEn: 'Amount (Rs)', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'payment_mode', labelMr: 'माध्यम', labelEn: 'Mode', flex: 1.0),
        ReportColumn(key: 'remarks', labelMr: 'शेरा', labelEn: 'Remarks', flex: 1.5),
      ],
    ),
    const ReportDefinition(
      id: 'savings_collection',
      titleMr: '८. बचत संकलन अहवाल (Savings Collection)',
      titleEn: '8. Savings Collection by Mode',
      subtitle: 'कॅश, बँक ट्रान्सफर व UPI नुसार बचत संकलन वर्गवारी',
      category: ReportCategory.savings,
      icon: Icons.payments,
      supabaseTable: 'savings',
      dateField: 'savings_date',
      columns: [
        ReportColumn(key: 'payment_mode', labelMr: 'भरणा प्रकार (Mode)', labelEn: 'Payment Mode', flex: 1.5),
        ReportColumn(key: 'transactions_count', labelMr: 'पावत्या संख्या', labelEn: 'Count', isNumeric: true, flex: 1.0),
        ReportColumn(key: 'total_collected', labelMr: 'एकूण संकलन (₹)', labelEn: 'Total Amount (Rs)', isNumeric: true, isCurrency: true, flex: 1.5),
        ReportColumn(key: 'share_percentage', labelMr: 'टक्केवारी (%)', labelEn: 'Share %', isNumeric: true, flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'pending_savings',
      titleMr: '९. थकीत बचत अहवाल (Pending Savings)',
      titleEn: '9. Pending Savings Report',
      subtitle: 'नियमित बचत न भरलेल्या सभासदांची यादी व रक्कम',
      category: ReportCategory.savings,
      icon: Icons.warning_amber_rounded,
      supabaseTable: 'savings',
      dateField: 'savings_date',
      columns: [
        ReportColumn(key: 'member_code', labelMr: 'आयडी', labelEn: 'Code', flex: 0.8),
        ReportColumn(key: 'member_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 2.0),
        ReportColumn(key: 'mobile', labelMr: 'मोबाईल', labelEn: 'Mobile', flex: 1.2),
        ReportColumn(key: 'pending_months', labelMr: 'थकीत महिने', labelEn: 'Pending Months', isNumeric: true, flex: 1.0),
        ReportColumn(key: 'pending_amount', labelMr: 'थकीत रक्कम (₹)', labelEn: 'Due Amount (Rs)', isNumeric: true, isCurrency: true, flex: 1.2),
      ],
    ),
    const ReportDefinition(
      id: 'annual_savings',
      titleMr: '१०. वार्षिक बचत अहवाल (Annual Savings)',
      titleEn: '10. Annual Savings Summary',
      subtitle: 'संपूर्ण आर्थिक वर्षातील महिनानिहाय बचत वाढ सारांश',
      category: ReportCategory.savings,
      icon: Icons.auto_graph,
      supabaseTable: 'savings',
      dateField: 'savings_date',
      columns: [
        ReportColumn(key: 'month_name', labelMr: 'महिना', labelEn: 'Month', flex: 1.2),
        ReportColumn(key: 'expected', labelMr: 'अपेक्षित (₹)', labelEn: 'Expected', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'collected', labelMr: 'संकलित (₹)', labelEn: 'Collected', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'pending', labelMr: 'थकीत (₹)', labelEn: 'Pending', isNumeric: true, isCurrency: true, flex: 1.0),
        ReportColumn(key: 'rate', labelMr: 'टक्केवारी', labelEn: 'Rate %', isNumeric: true, flex: 1.0),
      ],
    ),

    // --- 3. LOAN REPORTS ---
    const ReportDefinition(
      id: 'loan_report',
      titleMr: '११. कर्ज वाटप अहवाल (Loan Report)',
      titleEn: '11. Loan Report',
      subtitle: 'सर्व मंजूर व वाटप केलेल्या कर्जांची संपूर्ण यादी',
      category: ReportCategory.loans,
      icon: Icons.account_balance,
      supabaseTable: 'loans',
      dateField: 'disbursement_date',
      isLandscape: true,
      columns: [
        ReportColumn(key: 'loan_code', labelMr: 'कर्ज क्र.', labelEn: 'Loan No', flex: 1.0),
        ReportColumn(key: 'member_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 1.8),
        ReportColumn(key: 'approved_amount', labelMr: 'कर्ज रक्कम (₹)', labelEn: 'Amount', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'interest_rate', labelMr: 'व्याज %', labelEn: 'Rate %', isNumeric: true, flex: 0.8),
        ReportColumn(key: 'interest_type', labelMr: 'प्रकार', labelEn: 'EMI Type', flex: 1.0),
        ReportColumn(key: 'emi_amount', labelMr: 'मासिक हप्ता (₹)', labelEn: 'EMI Amt', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'outstanding_principal', labelMr: 'शिल्लक मुद्दल (₹)', labelEn: 'Outstanding', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 0.9),
      ],
    ),
    const ReportDefinition(
      id: 'loan_application',
      titleMr: '१२. कर्ज अर्ज अहवाल (Loan Application)',
      titleEn: '12. Loan Application Report',
      subtitle: 'कर्ज मागण्या, उद्देश व मंजुरी स्थिती',
      category: ReportCategory.loans,
      icon: Icons.post_add,
      supabaseTable: 'loans',
      dateField: 'application_date',
      columns: [
        ReportColumn(key: 'application_date', labelMr: 'अर्ज तारीख', labelEn: 'App Date', flex: 1.0),
        ReportColumn(key: 'member_name', labelMr: 'अर्जदार सदस्य', labelEn: 'Applicant', flex: 1.8),
        ReportColumn(key: 'requested_amount', labelMr: 'मागितलेली रक्कम (₹)', labelEn: 'Requested', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'purpose', labelMr: 'कर्ज कारण / उद्देश', labelEn: 'Purpose', flex: 1.5),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'emi_collection',
      titleMr: '१३. हप्ता वसुली अहवाल (EMI Collection)',
      titleEn: '13. EMI Collection Report',
      subtitle: 'वसुली झालेल्या हप्त्यांचे मुद्दल, व्याज व पावती तपशील',
      category: ReportCategory.loans,
      icon: Icons.receipt_long,
      supabaseTable: 'loan_emis',
      dateField: 'payment_date',
      isLandscape: true,
      columns: [
        ReportColumn(key: 'payment_date', labelMr: 'वसुली तारीख', labelEn: 'Pay Date', flex: 1.0),
        ReportColumn(key: 'receipt_number', labelMr: 'पावती क्र.', labelEn: 'Receipt No', flex: 1.2),
        ReportColumn(key: 'borrower_name', labelMr: 'कर्जदार नाव', labelEn: 'Borrower', flex: 1.8),
        ReportColumn(key: 'emi_number', labelMr: 'हप्ता क्र.', labelEn: 'EMI #', isNumeric: true, flex: 0.7),
        ReportColumn(key: 'principal', labelMr: 'मुद्दल (₹)', labelEn: 'Principal', isNumeric: true, isCurrency: true, flex: 1.0),
        ReportColumn(key: 'interest', labelMr: 'व्याज (₹)', labelEn: 'Interest', isNumeric: true, isCurrency: true, flex: 1.0),
        ReportColumn(key: 'paid_amount', labelMr: 'एकूण भरणा (₹)', labelEn: 'Total Paid', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'payment_mode', labelMr: 'माध्यम', labelEn: 'Mode', flex: 0.9),
      ],
    ),
    const ReportDefinition(
      id: 'pending_emi',
      titleMr: '१४. थकीत हप्ता अहवाल (Pending EMI)',
      titleEn: '14. Pending EMI Report',
      subtitle: 'हप्त्याची तारीख उलटून गेलेले व प्रलंबित कर्जदार',
      category: ReportCategory.loans,
      icon: Icons.schedule,
      supabaseTable: 'loan_emis',
      dateField: 'due_date',
      columns: [
        ReportColumn(key: 'due_date', labelMr: 'हप्ता तारीख', labelEn: 'Due Date', flex: 1.0),
        ReportColumn(key: 'borrower_name', labelMr: 'कर्जदार सदस्य', labelEn: 'Borrower', flex: 1.8),
        ReportColumn(key: 'emi_number', labelMr: 'हप्ता क्र.', labelEn: 'EMI #', isNumeric: true, flex: 0.7),
        ReportColumn(key: 'emi_amount', labelMr: 'हप्ता रक्कम (₹)', labelEn: 'EMI Amount', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'late_fee', labelMr: 'विलंब दंड (₹)', labelEn: 'Late Fee', isNumeric: true, isCurrency: true, flex: 1.0),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 0.9),
      ],
    ),
    const ReportDefinition(
      id: 'overdue_emi',
      titleMr: '१५. थकीत मुद्दल व व्याज अहवाल (Overdue Loans)',
      titleEn: '15. Overdue Loans & Defaulters',
      subtitle: 'दीर्घकाळ थकबाकीदार सभासद व संचित व्याज विलंब',
      category: ReportCategory.loans,
      icon: Icons.report_problem,
      supabaseTable: 'loans',
      dateField: 'application_date',
      columns: [
        ReportColumn(key: 'loan_code', labelMr: 'कर्ज कोड', labelEn: 'Loan Code', flex: 1.0),
        ReportColumn(key: 'member_name', labelMr: 'कर्जदार नाव', labelEn: 'Borrower', flex: 2.0),
        ReportColumn(key: 'approved_amount', labelMr: 'कर्ज रक्कम (₹)', labelEn: 'Sanctioned', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'outstanding_principal', labelMr: 'शिल्लक मुद्दल (₹)', labelEn: 'Outstanding', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'overdue_emis_count', labelMr: 'थकीत हप्ते', labelEn: 'Missed EMIs', isNumeric: true, flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'loan_history',
      titleMr: '१६. बंद झालेली कर्जे (Loan History)',
      titleEn: '16. Loan Settlement History',
      subtitle: 'पूर्ण परतफेड झालेली व बंद करण्यात आलेली कर्जे',
      category: ReportCategory.loans,
      icon: Icons.check_circle_outline,
      supabaseTable: 'loans',
      dateField: 'settlement_date',
      columns: [
        ReportColumn(key: 'loan_code', labelMr: 'कर्ज कोड', labelEn: 'Loan Code', flex: 1.0),
        ReportColumn(key: 'member_name', labelMr: 'कर्जदार नाव', labelEn: 'Member Name', flex: 2.0),
        ReportColumn(key: 'approved_amount', labelMr: 'कर्ज रक्कम (₹)', labelEn: 'Amount', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'total_repaid', labelMr: 'एकूण परतफेड (₹)', labelEn: 'Total Repaid', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'settlement_date', labelMr: 'बंद दिनांक', labelEn: 'Settled Date', flex: 1.2),
      ],
    ),
    const ReportDefinition(
      id: 'loan_summary',
      titleMr: '१७. कर्ज ताळेबंद सारांश (Loan Portfolio)',
      titleEn: '17. Loan Portfolio Summary',
      subtitle: 'एकूण वाटप, चालू मुद्दल, वसूल व्याज व थकीत प्रमाण',
      category: ReportCategory.loans,
      icon: Icons.pie_chart,
      supabaseTable: 'loans',
      dateField: 'application_date',
      columns: [
        ReportColumn(key: 'metric_name', labelMr: 'कर्ज निर्देशांक (Metric)', labelEn: 'Loan Metric', flex: 2.5),
        ReportColumn(key: 'count', labelMr: 'संख्या', labelEn: 'Count', isNumeric: true, flex: 1.0),
        ReportColumn(key: 'amount', labelMr: 'रक्कम (₹)', labelEn: 'Amount (Rs)', isNumeric: true, isCurrency: true, flex: 1.5),
      ],
    ),

    // --- 4. FINANCIAL REPORTS ---
    const ReportDefinition(
      id: 'income_report',
      titleMr: '१८. उत्पन्न अहवाल (Income Report)',
      titleEn: '18. Income Report',
      subtitle: 'कर्ज व्याज, वर्गणी, दंड व इतर जमा उत्पन्न',
      category: ReportCategory.financial,
      icon: Icons.arrow_circle_up_rounded,
      supabaseTable: 'incomes',
      dateField: 'income_date',
      columns: [
        ReportColumn(key: 'income_date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'category', labelMr: 'उत्पन्न प्रवर्ग (Category)', labelEn: 'Category', flex: 1.8),
        ReportColumn(key: 'amount', labelMr: 'जमा रक्कम (₹)', labelEn: 'Amount', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'received_from', labelMr: 'कोणाकडून मिळाले', labelEn: 'Received From', flex: 1.8),
        ReportColumn(key: 'payment_mode', labelMr: 'माध्यम', labelEn: 'Mode', flex: 0.9),
      ],
    ),
    const ReportDefinition(
      id: 'expense_report',
      titleMr: '१९. खर्च अहवाल (Expense Report)',
      titleEn: '19. Expense Report',
      subtitle: 'स्टेशनरी, प्रवास, मेळावा व प्रशासकीय खर्च तपशील',
      category: ReportCategory.financial,
      icon: Icons.arrow_circle_down_rounded,
      supabaseTable: 'expenses',
      dateField: 'expense_date',
      columns: [
        ReportColumn(key: 'expense_date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'category', labelMr: 'खर्च प्रकार (Category)', labelEn: 'Category', flex: 1.8),
        ReportColumn(key: 'amount', labelMr: 'खर्च रक्कम (₹)', labelEn: 'Amount', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'paid_to', labelMr: 'कोणास दिले', labelEn: 'Paid To', flex: 1.8),
        ReportColumn(key: 'payment_mode', labelMr: 'माध्यम', labelEn: 'Mode', flex: 0.9),
      ],
    ),
    const ReportDefinition(
      id: 'profit_loss',
      titleMr: '२०. नफा-तोटा पत्रक (Profit & Loss)',
      titleEn: '20. Profit & Loss Statement',
      subtitle: 'एकूण जमा उत्पन्न vs खर्च = निव्वळ वाटपयोग्य नफा',
      category: ReportCategory.financial,
      icon: Icons.analytics,
      supabaseTable: 'incomes',
      dateField: 'income_date',
      columns: [
        ReportColumn(key: 'particulars', labelMr: 'तपशील (Particulars)', labelEn: 'Particulars', flex: 2.5),
        ReportColumn(key: 'amount', labelMr: 'रक्कम (₹)', labelEn: 'Amount (Rs)', isNumeric: true, isCurrency: true, flex: 1.5),
        ReportColumn(key: 'notes', labelMr: 'शेरा / स्पष्टीकरण', labelEn: 'Notes', flex: 2.0),
      ],
    ),
    const ReportDefinition(
      id: 'cash_flow',
      titleMr: '२१. कॅश फ्लो स्टेटमेंट (Cash Flow)',
      titleEn: '21. Cash Flow Statement',
      subtitle: 'रोख आवक (Inflow) व रोख जावक (Outflow) विश्लेषण',
      category: ReportCategory.financial,
      icon: Icons.swap_horiz,
      supabaseTable: 'cash_book',
      dateField: 'entry_date',
      columns: [
        ReportColumn(key: 'entry_date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'type', labelMr: 'प्रकार (In/Out)', labelEn: 'Flow Type', flex: 1.0),
        ReportColumn(key: 'description', labelMr: 'तपशील', labelEn: 'Description', flex: 2.5),
        ReportColumn(key: 'amount', labelMr: 'रक्कम (₹)', labelEn: 'Amount', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'balance_after', labelMr: 'शिल्लक (₹)', labelEn: 'Balance After', isNumeric: true, isCurrency: true, flex: 1.2),
      ],
    ),

    // --- 5. BANK & CASH REPORTS ---
    const ReportDefinition(
      id: 'bank_accounts',
      titleMr: '२२. बँक खाती अहवाल (Bank Accounts)',
      titleEn: '22. Bank Account Balances',
      subtitle: 'गटाची विविध बँकांमधील खाती, क्रमांक व चालू शिल्लक',
      category: ReportCategory.bankCash,
      icon: Icons.account_balance,
      supabaseTable: 'bank_accounts',
      dateField: 'created_at',
      columns: [
        ReportColumn(key: 'bank_name', labelMr: 'बँकेचे नाव', labelEn: 'Bank Name', flex: 2.0),
        ReportColumn(key: 'account_number', labelMr: 'खाते क्रमांक', labelEn: 'Account Number', flex: 1.8),
        ReportColumn(key: 'ifsc', labelMr: 'IFSC कोड', labelEn: 'IFSC', flex: 1.2),
        ReportColumn(key: 'account_type', labelMr: 'प्रकार', labelEn: 'Type', flex: 1.0),
        ReportColumn(key: 'current_balance', labelMr: 'चालू शिल्लक (₹)', labelEn: 'Balance', isNumeric: true, isCurrency: true, flex: 1.5),
      ],
    ),
    const ReportDefinition(
      id: 'bank_transactions',
      titleMr: '२३. बँक व्यवहार अहवाल (Bank Transactions)',
      titleEn: '23. Bank Transaction Passbook',
      subtitle: 'बँकेतील जमा (ठेव) व काढलेली रक्कम (चेक/RTGS/UPI)',
      category: ReportCategory.bankCash,
      icon: Icons.receipt,
      supabaseTable: 'bank_transactions',
      dateField: 'transaction_date',
      columns: [
        ReportColumn(key: 'transaction_date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'description', labelMr: 'तपशील', labelEn: 'Description', flex: 2.2),
        ReportColumn(key: 'deposit', labelMr: 'जमा / Deposit (₹)', labelEn: 'Deposit', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'withdrawal', labelMr: 'नावे / Withdrawal (₹)', labelEn: 'Withdrawal', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'balance', labelMr: 'शिल्लक (₹)', labelEn: 'Balance', isNumeric: true, isCurrency: true, flex: 1.2),
      ],
    ),
    const ReportDefinition(
      id: 'cash_book',
      titleMr: '२४. रोकड वही अहवाल (Cash Book)',
      titleEn: '24. Cash Book Report',
      subtitle: 'रोजच्या रोख जमा-खर्च नोंदी व हातातील रोख ताळेबंद',
      category: ReportCategory.bankCash,
      icon: Icons.menu_book,
      supabaseTable: 'cash_book',
      dateField: 'entry_date',
      columns: [
        ReportColumn(key: 'entry_date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'description', labelMr: 'तपशील', labelEn: 'Particulars', flex: 2.2),
        ReportColumn(key: 'cash_in', labelMr: 'जमा / Cash In (₹)', labelEn: 'Cash In', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'cash_out', labelMr: 'खर्च / Cash Out (₹)', labelEn: 'Cash Out', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'balance_after', labelMr: 'शिल्लक (₹)', labelEn: 'Balance', isNumeric: true, isCurrency: true, flex: 1.2),
      ],
    ),
    const ReportDefinition(
      id: 'bank_reconciliation',
      titleMr: '२५. बँक मेळ अहवाल (Reconciliation)',
      titleEn: '25. Bank Reconciliation',
      subtitle: 'कॅश बुक व बँक पासबुक मधील रकमेचा ताळमेळ',
      category: ReportCategory.bankCash,
      icon: Icons.fact_check,
      supabaseTable: 'bank_reconciliations',
      dateField: 'reconciliation_date',
      columns: [
        ReportColumn(key: 'reconciliation_date', labelMr: 'मेळ तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'statement_balance', labelMr: 'पासबुक शिल्लक (₹)', labelEn: 'Bank Balance', isNumeric: true, isCurrency: true, flex: 1.5),
        ReportColumn(key: 'book_balance', labelMr: 'वही शिल्लक (₹)', labelEn: 'Book Balance', isNumeric: true, isCurrency: true, flex: 1.5),
        ReportColumn(key: 'difference', labelMr: 'तफावत (₹)', labelEn: 'Difference', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 1.0),
      ],
    ),

    // --- 6. BUSINESS & SALES REPORTS ---
    const ReportDefinition(
      id: 'product_sales',
      titleMr: '२६. उत्पादन विक्री अहवाल (Product Sales)',
      titleEn: '26. Product Sales Report',
      subtitle: 'पापड, लोणचे, मसाले व हस्तकला वस्तू विक्री उत्पन्न',
      category: ReportCategory.business,
      icon: Icons.store,
      supabaseTable: 'sales',
      dateField: 'sale_date',
      columns: [
        ReportColumn(key: 'sale_date', labelMr: 'विक्री तारीख', labelEn: 'Sale Date', flex: 1.0),
        ReportColumn(key: 'invoice_number', labelMr: 'बिल क्र.', labelEn: 'Bill No', flex: 1.0),
        ReportColumn(key: 'customer_name', labelMr: 'ग्राहक नाव', labelEn: 'Customer', flex: 1.8),
        ReportColumn(key: 'total_amount', labelMr: 'एकूण रक्कम (₹)', labelEn: 'Amount', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'payment_status', labelMr: 'भरणा स्थिती', labelEn: 'Status', flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'inventory_stock',
      titleMr: '२७. स्टॉक व इन्व्हेंटरी अहवाल (Inventory)',
      titleEn: '27. Inventory & Stock Report',
      subtitle: 'कच्चा माल, तयार माल व शिल्लक साठा यादी',
      category: ReportCategory.business,
      icon: Icons.inventory,
      supabaseTable: 'products',
      dateField: 'updated_at',
      columns: [
        ReportColumn(key: 'name', labelMr: 'उत्पादनाचे नाव', labelEn: 'Product Name', flex: 2.0),
        ReportColumn(key: 'category', labelMr: 'प्रवर्ग', labelEn: 'Category', flex: 1.2),
        ReportColumn(key: 'current_stock', labelMr: 'शिल्लक साठा', labelEn: 'Current Stock', isNumeric: true, flex: 1.0),
        ReportColumn(key: 'unit', labelMr: 'युनिट', labelEn: 'Unit', flex: 0.8),
        ReportColumn(key: 'selling_price', labelMr: 'विक्री दर (₹)', labelEn: 'Price (Rs)', isNumeric: true, isCurrency: true, flex: 1.2),
      ],
    ),
    const ReportDefinition(
      id: 'business_report',
      titleMr: '२८. सदस्य उद्योग अहवाल (Member Business)',
      titleEn: '28. Member Business Report',
      subtitle: 'गटातील महिलांचे वैयक्तिक व सामूहिक गृहउद्योग',
      category: ReportCategory.business,
      icon: Icons.business_center,
      supabaseTable: 'member_businesses',
      dateField: 'created_at',
      columns: [
        ReportColumn(key: 'member_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 2.0),
        ReportColumn(key: 'business_name', labelMr: 'उद्योगाचे नाव', labelEn: 'Business Name', flex: 2.0),
        ReportColumn(key: 'business_type', labelMr: 'प्रकार', labelEn: 'Type', flex: 1.2),
        ReportColumn(key: 'monthly_turnover', labelMr: 'मासिक उलाढाल (₹)', labelEn: 'Turnover', isNumeric: true, isCurrency: true, flex: 1.4),
      ],
    ),

    // --- 7. MEETING REPORTS ---
    const ReportDefinition(
      id: 'meeting_report',
      titleMr: '२९. बैठका अहवाल (Meeting Report)',
      titleEn: '29. Meetings & Sessions',
      subtitle: 'मासिक सभांची यादी, विषय, ठिकाण व इतिवृत्त',
      category: ReportCategory.meetings,
      icon: Icons.meeting_room,
      supabaseTable: 'meetings',
      dateField: 'meeting_date',
      columns: [
        ReportColumn(key: 'meeting_date', labelMr: 'सभा तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'meeting_type', labelMr: 'प्रकार', labelEn: 'Type', flex: 1.0),
        ReportColumn(key: 'agenda', labelMr: 'विषयपत्रिका / अजेंडा', labelEn: 'Agenda', flex: 2.5),
        ReportColumn(key: 'location', labelMr: 'ठिकाण', labelEn: 'Venue', flex: 1.5),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'resolutions_report',
      titleMr: '३०. ठराव वही अहवाल (Resolutions)',
      titleEn: '30. Resolutions & Minutes',
      subtitle: 'सभेत मंजूर झालेले ठराव, निर्णय व मतदान नोंद',
      category: ReportCategory.meetings,
      icon: Icons.how_to_vote,
      supabaseTable: 'resolutions',
      dateField: 'created_at',
      columns: [
        ReportColumn(key: 'resolution_number', labelMr: 'ठराव क्र.', labelEn: 'Res. No', flex: 0.8),
        ReportColumn(key: 'title', labelMr: 'ठरावाचा विषय', labelEn: 'Subject', flex: 2.5),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 1.0),
        ReportColumn(key: 'votes_in_favor', labelMr: 'अनुकूल', labelEn: 'Favor', isNumeric: true, flex: 0.8),
        ReportColumn(key: 'votes_against', labelMr: 'प्रतिकूल', labelEn: 'Against', isNumeric: true, flex: 0.8),
      ],
    ),

    // --- 8. GOVERNANCE, FINES & OTHER REPORTS ---
    const ReportDefinition(
      id: 'contributions',
      titleMr: '३१. वर्गणी अहवाल (Contributions)',
      titleEn: '31. Fund Contributions',
      subtitle: 'सण, उत्सव व आपत्कालीन निधी विशेष वर्गणी जमा',
      category: ReportCategory.governance,
      icon: Icons.volunteer_activism,
      supabaseTable: 'contributions',
      dateField: 'contribution_date',
      columns: [
        ReportColumn(key: 'contribution_date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'member_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 2.0),
        ReportColumn(key: 'cause', labelMr: 'निधी कारण / हेतू', labelEn: 'Cause / Purpose', flex: 2.0),
        ReportColumn(key: 'amount', labelMr: 'रक्कम (₹)', labelEn: 'Amount', isNumeric: true, isCurrency: true, flex: 1.2),
      ],
    ),
    const ReportDefinition(
      id: 'fines',
      titleMr: '३२. दंड व विलंब शुल्क अहवाल (Fines)',
      titleEn: '32. Fines & Penalties',
      subtitle: 'सभेस गैरहजर दंड, उशिरा बचत दंड व वसुली',
      category: ReportCategory.governance,
      icon: Icons.gavel,
      supabaseTable: 'fines',
      dateField: 'fine_date',
      columns: [
        ReportColumn(key: 'fine_date', labelMr: 'तारीख', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'member_name', labelMr: 'सदस्याचे नाव', labelEn: 'Member Name', flex: 2.0),
        ReportColumn(key: 'reason', labelMr: 'दंडाचे कारण', labelEn: 'Reason', flex: 2.0),
        ReportColumn(key: 'amount', labelMr: 'दंड रक्कम (₹)', labelEn: 'Fine Amt', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'is_paid', labelMr: 'भरणा स्थिती', labelEn: 'Status', flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'government_schemes',
      titleMr: '३३. शासकीय योजना अहवाल (Govt Schemes)',
      titleEn: '33. Government Schemes',
      subtitle: 'उमेद, MSRLM व नाबार्ड अनुदान अर्ज व स्थिती',
      category: ReportCategory.governance,
      icon: Icons.assured_workload,
      supabaseTable: 'scheme_applications',
      dateField: 'application_date',
      columns: [
        ReportColumn(key: 'application_date', labelMr: 'अर्ज दिनांक', labelEn: 'Date', flex: 1.0),
        ReportColumn(key: 'scheme_name', labelMr: 'योजनेचे नाव', labelEn: 'Scheme Name', flex: 2.5),
        ReportColumn(key: 'grant_amount', labelMr: 'अनुदान रक्कम (₹)', labelEn: 'Grant (Rs)', isNumeric: true, isCurrency: true, flex: 1.4),
        ReportColumn(key: 'status', labelMr: 'स्थिती', labelEn: 'Status', flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'trainings',
      titleMr: '३४. कौशल्य प्रशिक्षण अहवाल (Trainings)',
      titleEn: '34. Skill Trainings',
      subtitle: 'महिलांसाठी आयोजित शिवणकाम, खाद्यप्रक्रिया कार्यशाळा',
      category: ReportCategory.governance,
      icon: Icons.school,
      supabaseTable: 'trainings',
      dateField: 'start_date',
      columns: [
        ReportColumn(key: 'start_date', labelMr: 'सुरुवात तारीख', labelEn: 'Start Date', flex: 1.0),
        ReportColumn(key: 'training_title', labelMr: 'प्रशिक्षण विषय', labelEn: 'Training Title', flex: 2.5),
        ReportColumn(key: 'trainer_name', labelMr: 'मार्गदर्शक', labelEn: 'Trainer', flex: 1.5),
        ReportColumn(key: 'participants_count', labelMr: 'सहभागी महिला', labelEn: 'Participants', isNumeric: true, flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'events',
      titleMr: '३५. मेळावा व उपक्रम अहवाल (Events)',
      titleEn: '35. Events & Activities',
      subtitle: 'महिला दिन, प्रदर्शन व बचत गट मेळावा सहभाग',
      category: ReportCategory.governance,
      icon: Icons.celebration,
      supabaseTable: 'events',
      dateField: 'event_date',
      columns: [
        ReportColumn(key: 'event_date', labelMr: 'तारीख', labelEn: 'Event Date', flex: 1.0),
        ReportColumn(key: 'title', labelMr: 'उपक्रमाचे नाव', labelEn: 'Event Name', flex: 2.5),
        ReportColumn(key: 'venue', labelMr: 'ठिकाण', labelEn: 'Venue', flex: 1.5),
        ReportColumn(key: 'budget', labelMr: 'खर्च (₹)', labelEn: 'Cost (Rs)', isNumeric: true, isCurrency: true, flex: 1.0),
      ],
    ),
    const ReportDefinition(
      id: 'audit_logs',
      titleMr: '३६. सिस्टीम ऑडिट लॉग अहवाल (Audit Logs)',
      titleEn: '36. Security Audit Log',
      subtitle: 'नोंदींमधील बदल, लॉगिन व व्यवस्थापकीय फेरबदल ऑडिट',
      category: ReportCategory.governance,
      icon: Icons.security,
      supabaseTable: 'audit_logs',
      dateField: 'created_at',
      columns: [
        ReportColumn(key: 'created_at', labelMr: 'दिनांक व वेळ', labelEn: 'Timestamp', flex: 1.2),
        ReportColumn(key: 'user_name', labelMr: 'वापरकर्ता', labelEn: 'User', flex: 1.5),
        ReportColumn(key: 'action', labelMr: 'कृती (Action)', labelEn: 'Action', flex: 1.0),
        ReportColumn(key: 'entity_name', labelMr: 'मॉड्यूल', labelEn: 'Entity', flex: 1.2),
        ReportColumn(key: 'details', labelMr: 'तपशील', labelEn: 'Details', flex: 2.0),
      ],
    ),

    // --- 9. MANAGEMENT & ANNUAL REPORTS ---
    const ReportDefinition(
      id: 'monthly_management',
      titleMr: '३७. मासिक व्यवस्थापन अहवाल (Monthly Management)',
      titleEn: '37. Monthly Management Dossier',
      subtitle: 'महिन्यातील सर्व व्यवहार, बचत, कर्ज व नफ्याचा एकत्रीत अहवाल',
      category: ReportCategory.management,
      icon: Icons.summarize,
      supabaseTable: 'groups',
      dateField: 'created_at',
      columns: [
        ReportColumn(key: 'metric', labelMr: 'व्यवस्थापकीय घटक', labelEn: 'Management Metric', flex: 2.5),
        ReportColumn(key: 'count', labelMr: 'संख्या', labelEn: 'Count', isNumeric: true, flex: 1.0),
        ReportColumn(key: 'amount', labelMr: 'रक्कम (₹)', labelEn: 'Amount (Rs)', isNumeric: true, isCurrency: true, flex: 1.5),
        ReportColumn(key: 'status', labelMr: 'शेरा', labelEn: 'Status / Note', flex: 1.5),
      ],
    ),
    const ReportDefinition(
      id: 'annual_report',
      titleMr: '३८. वार्षिक सर्वसाधारण सभा अहवाल (Annual Report)',
      titleEn: '38. Annual Comprehensive Report',
      subtitle: 'वार्षिक ताळेबंद, नफा वाटप व आगामी वर्षाचे नियोजन',
      category: ReportCategory.management,
      icon: Icons.workspace_premium,
      supabaseTable: 'groups',
      dateField: 'created_at',
      isLandscape: true,
      columns: [
        ReportColumn(key: 'section', labelMr: 'विभाग (Section)', labelEn: 'Section', flex: 1.8),
        ReportColumn(key: 'description', labelMr: 'वार्षिक तपशील', labelEn: 'Annual Particulars', flex: 2.5),
        ReportColumn(key: 'opening', labelMr: 'आरंभी शिल्लक (₹)', labelEn: 'Opening (Rs)', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'during_year', labelMr: 'वर्षभरातील जमा (₹)', labelEn: 'During Year', isNumeric: true, isCurrency: true, flex: 1.2),
        ReportColumn(key: 'closing', labelMr: 'अखेर शिल्लक (₹)', labelEn: 'Closing (Rs)', isNumeric: true, isCurrency: true, flex: 1.2),
      ],
    ),
  ];
  static List<ReportDefinition> getReportsByCategory(ReportCategory category) {
    return allReports.where((r) => r.category == category).toList();
  }

  static ReportDefinition? getReportById(String id) {
    for (var r in allReports) {
      if (r.id == id) return r;
    }
    return null;
  }
}
